// Copyright 2020-2021 Aumoa.lib. All right reserved.

#pragma once

#include "CoreMinimal.h"
#include "RenderMinimal.h"
#include "GameEnums.h"
#include "GameStructures.h"
#include "SubclassOf.h"
#include "GameFramework/Actor.h"
#include "Misc/Paths.h"
#include "Assets/SoftObjectPtr.h"
#include "Layout/TransformCalculus2D.h"
#include "Layout/SlateRenderTransform.h"
#include "Layout/Scale2D.h"
#include "Layout/Shear2D.h"
#include "Layout/SlateLayoutTransform.h"
#include "Layout/Geometry.h"
#include "Layout/ArrangedWidget.h"
#include "Layout/LayoutGeometry.h"
#include "Layout/PaintGeometry.h"
#include "Layout/Anchors.h"
#include "Layout/SizeParam.h"
#include "Layout/LayoutImpl.h"
#include "Widgets/Widget.h"
#include "Draw/SlateBrush.h"
#include "Draw/SlateDrawElement.h"