// Copyright 2020-2021 Aumoa.lib. All right reserved.

#pragma once

#include "CoreMinimal.h"

DECLARE_LOG_CATEGORY(GAME_API, LogEngine);
DECLARE_LOG_CATEGORY(GAME_API, LogTicking);
DECLARE_LOG_CATEGORY(GAME_API, LogPawn);
DECLARE_LOG_CATEGORY(GAME_API, LogSceneComponent);
DECLARE_LOG_CATEGORY(GAME_API, LogController);
DECLARE_LOG_CATEGORY(GAME_API, LogWorld);
DECLARE_LOG_CATEGORY(GAME_API, LogCamera);
DECLARE_LOG_CATEGORY(GAME_API, LogComponent);
DECLARE_LOG_CATEGORY(GAME_API, LogAssets);
DECLARE_LOG_CATEGORY(GAME_API, LogMaterial);
DECLARE_LOG_CATEGORY(GAME_API, LogStaticMesh);
DECLARE_LOG_CATEGORY(GAME_API, LogPlayerController);
DECLARE_LOG_CATEGORY(GAME_API, LogModule);