// Copyright 2020-2022 Aumoa.lib. All right reserved.

#pragma once

#include "PrimitiveTypes.h"
#include "Object.h"
#include "Casts.h"
#include "CoreAssert.h"
#include "ValueType.h"
#include "IDisposable.h"
#include "CoreConcepts.h"
#include "LogCore.h"
#include "GC/GC.h"
#include "GC/SharedPtr.h"
#include "GC/WeakPtr.h"
#include "Attributes/AttributeClass.h"
#include "Attributes/AttributeField.h"
#include "Reflection/ReflectionMacros.h"
#include "Reflection/Type.h"
#include "Reflection/FieldInfo.h"
#include "Reflection/SubclassOf.h"
#include "Reflection/Enum.h"
#include "Reflection/Assembly.h"
#include "Delegates/MulticastDelegate.h"
#include "Delegates/MulticastEvent.h"
#include "Diagnostics/CycleCounterMacros.h"
#include "Diagnostics/LogCategory.h"
#include "Diagnostics/LogSystem.h"
#include "Diagnostics/LogVerbosity.h"
#include "Diagnostics/CycleCounterNamespace.h"
#include "Diagnostics/CycleCounterUnit.h"
#include "Misc/PlatformMacros.h"
#include "Misc/NonCopyable.h"
#include "Misc/String.h"
#include "Misc/DateTime.h"
#include "Misc/InputEnums.h"
#include "Threading/Task.h"
#include "Threading/TaskCompletionSource.h"

#include "Reflection/TypeInfoMetadataGenerator.Impl.h"
#include "Reflection/FieldInfoMetadataGenerator.Impl.h"