<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>..\..\..\Binaries\DotNET\</OutputPath>
    <EnableDefaultNamespace>false</EnableDefaultNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RootNamespace>AylaEngine</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

</Project>
