// Copyright 2020-2021 Aumoa.lib. All right reserved.

#pragma once

#include "PrimitiveTypes.h"
#include "Object.h"
#include "Interface.h"
#include "CoreAssert.h"
#include "Concepts/CoreConcepts.h"
#include "Delegates/MulticastDelegate.h"
#include "Delegates/MulticastEvent.h"
#include "Diagnostics/LogCategory.h"
#include "Diagnostics/LogSystem.h"
#include "Diagnostics/LogVerbosity.h"
#include "Mathematics/MathEx.h"
#include "Mathematics/Degrees.h"
#include "Mathematics/Radians.h"
#include "Numerics/Vector.h"
#include "Numerics/Matrix.h"
#include "Numerics/Matrix4x4.h"
#include "Numerics/Matrix2x2.h"
#include "Numerics/Matrix3x2.h"
#include "Numerics/AxisAlignedCube.h"
#include "Numerics/Color.h"
#include "Numerics/Frustum.h"
#include "Numerics/Line.h"
#include "Numerics/ObjectOrientedCube.h"
#include "Numerics/Plane.h"
#include "Numerics/Quaternion.h"
#include "Numerics/Complex.h"
#include "Numerics/Range.h"
#include "Numerics/Ray.h"
#include "Numerics/Sphere.h"
#include "Numerics/Rect.h"
#include "Misc/StringUtils.h"
#include "PlatformMisc/InputEnums.h"