// Copyright 2020-2022 Aumoa.lib. All right reserved.

#pragma once

#include "Core.h"
#include "Object.h"
#include "Type.h"
#include "Casts.h"
#include "CoreAssert.h"
#include "GC.h"
#include "DateTime.h"
#include "TimeSpan.h"
#include "IDisposable.h"
#include "LogCore.h"
#include "SubclassOf.h"
#include "Generic/IString.h"
#include "Delegates/MulticastDelegate.h"
#include "Delegates/MulticastEvent.h"
#include "Misc/StringBuilder.h"
#include "Logging/Log.h"
#include "Numerics/VectorInterface/Vector.h"
#include "Numerics/MatrixInterface/Matrix.h"
#include "Numerics/TransformInterface/Transform.h"
#include "Numerics/TransformInterface/Transform2D.h"
#include "Threading/Tasks/Task.h"
#include "CoreObject/WeakPtr.h"
#include "CoreObject/RefPtr.h"
#include "Exceptions/FormatException.h"
#include "Exceptions/ArgumentException.h"