// Copyright 2020-2025 Aumoa.lib. All right reserved.

#include "CoreMinimal.h"
#include "WindowsLaunch.h"

ACLASS__IMPL_CLASS_REGISTER_2(GENERATED_BODY__IMPL__RUNTIME_WINDOWSLAUNCH_PRIVATE_WINDOWS_WINDOWSLAUNCH_H__18__NAMESPACE, GENERATED_BODY__IMPL__RUNTIME_WINDOWSLAUNCH_PRIVATE_WINDOWS_WINDOWSLAUNCH_H__18__CLASSNAME);

namespace GENERATED_BODY__IMPL__RUNTIME_WINDOWSLAUNCH_PRIVATE_WINDOWS_WINDOWSLAUNCH_H__18__NAMESPACE
{
	void GENERATED_BODY__IMPL__RUNTIME_WINDOWSLAUNCH_PRIVATE_WINDOWS_WINDOWSLAUNCH_H__18__CLASSNAME::GatherProperties(::Ayla::PropertyCollector& collector)
	{
		Super::GatherProperties(collector);
	}
}