// Copyright 2020-2021 Aumoa.lib. All right reserved.

#pragma once

#include "PrimitiveTypes.h"
#include "Object.h"
#include "Concepts/SupportsObject.h"
#include "Delegates/MulticastDelegate.h"
#include "Delegates/MulticastEvent.h"
#include "Diagnostics/LogCategory.h"
#include "Diagnostics/LogSystem.h"
#include "Diagnostics/LogVerbosity.h"
#include "Mathematics/MathEx.h"
#include "Mathematics/Degrees.h"
#include "Mathematics/Radians.h"
#include "Numerics/Vector.h"
#include "Numerics/Vector2.h"
#include "Numerics/Vector3.h"
#include "Numerics/Vector4.h"
#include "Numerics/Matrix.h"
#include "Numerics/Matrix4x4.h"
#include "Numerics/AxisAlignedCube.h"
#include "Numerics/Color.h"
#include "Numerics/Frustum.h"
#include "Numerics/Line.h"
#include "Numerics/ObjectOrientedCube.h"
#include "Numerics/Plane.h"
#include "Numerics/Quaternion.h"
#include "Numerics/Range.h"
#include "Numerics/Ray.h"
#include "Numerics/Sphere.h"
#include "Utilities/DateTime.h"
#include "Utilities/StringUtils.h"
#include "Utilities/UniqueType.h"