<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <EnableDefaultNamespace>false</EnableDefaultNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RootNamespace>AylaEngine.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AylaBuildTool\AylaBuildTool.csproj" />
  </ItemGroup>

</Project>
