name: Check Compile Errors

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            xorg-dev \
            libxext-dev \
            libxrandr-dev \
            libxi-dev \
            libicu-dev \
            liburing-dev \
            libunwind-dev

      - name: Build AylaBuildTool
        run: dotnet publish ./Engine/Source/Programs/AylaBuildTool/AylaBuildTool.csproj -c Shipping -o ./Engine/Binaries/DotNET

      - name: Build
        run: dotnet ./Engine/Binaries/DotNET/AylaBuildTool.dll build --target "Engine" --config Shipping --skip-shaders

      - name: Run unit tests
        run: dotnet ./Engine/Binaries/DotNET/AylaBuildTool.dll test --target "AylaUnitTests" --config Shipping --skip-shaders
